version: 2.1
    

executors:
  python-executor:
    docker:
      - image: circleci/python:3.6

commands:
  docker_pull:
    steps:
    - run: echo "Pulling docker image"

  deploy_to_kubernetes:
    steps:
    - run: echo "Deploying to Kubernetes"

jobs:
  build:
    executor: python-executor
    steps:
    - checkout
    - run: echo "Linting..."
    - run: echo "Running Unit Test..."
    - run: echo "Building docker Image...."
    - run: echo "Running Component tests..."
    - run: echo "pushing docker image to ECS..."

  test:
    executor: python-executor
    steps:
    - docker_pull
    - deploy_to_kubernetes
    - run: echo "Run Integration tests"

  run-qa:
    executor: python-executor
    steps:
    - docker-pull
    - deploy-to-kubernetes
    - run: echo "Run Automated QA Tests"
    - run: echo "Run Manual QA Tests"

  staging:
    executor: python-executor
    steps:
    - run: echo "pull docker image"
    - run: echo "Deploy to kubernetes"
    - run: echo "Run Stree Tests"
    - run: echo "Run Manual QA Tests"

  production:
    executor: python-executor
    steps:
    - run: echo "pull docker image"
    - run: echo "Deploy to kubernetes"
    - run: echo "Run Smoke Tests"


workflows:
  version: 2.1
  build-and-test:
    jobs:
    - build
    - test:
        requires: build
    - run-qa:
        type: approval
        requires: test
    - approve-qa:
        type: approval
        requires: run-qa
    - deploy-to-staging:
        type: approval
        requires: approve-qa


