version: 2.1
    

executors:
  python-executor:
    docker:
      - image: circleci/python:3.6

commands:
  docker-pull:
    steps:
    - run: echo "Pulling docker image"

  deploy-to-kubernetes:
    steps:
    - run: echo "Deploying to Kubernetes"
    - run: echo "Tagging stage to github"

jobs:
  build:
    executor: python-executor
    steps:
    - checkout
    - run: echo "Linting"
    - run: echo "Running Unit Test"
    - run: echo "Building docker image"
    - run: echo "Running Component tests on docker container"
    - run: echo "Pushing versioned docker image to ECS"

  deploy-to-ci:
    executor: python-executor
    steps:
    - docker-pull
    - deploy-to-kubernetes

  run-integration-tests:
    executor: python-executor
    steps:
    - run: echo "Running automated integration tests"

  tag-qa:
    executor: python-executor
    steps:
            - run: echo "Hello"

  deploy-to-qa:
    executor: python-executor
    steps:
    - docker-pull
    - deploy-to-kubernetes

  run-automated-qa-tests:
    executor: python-executor
    steps:
    - docker-pull
    - deploy-to-kubernetes
    - run: echo "Run Automated QA Tests"


  staging:
    executor: python-executor
    steps:
    - run: echo "pull docker image"
    - run: echo "Deploy to kubernetes"
    - run: echo "Run Stree Tests"
    - run: echo "Run Manual QA Tests"

  production:
    executor: python-executor
    steps:
    - run: echo "pull docker image"
    - run: echo "Deploy to kubernetes"
    - run: echo "Run Smoke Tests"


workflows:
  version: 2.1

  ci:
    jobs:
    - build
    - deploy-to-ci:
        requires:
        - build
    - run-integration-tests:
        requires:
        - deploy-to-ci
    - tag-qa:
        requires:
        - run-integration-tests

  qa:
    jobs:
    - confirm-run-qa:
        type: approval
        filters:
          tags:
            only: qa-v\d+\.\d+\.\d+$


    - deploy-to-qa:
        requires:
        - confirm-run-qa

    - run-automated-qa-tests:
        requires:
        - deploy-to-qa

    - confirm-qa-ok:
        type: approval
        requires:
        - run-automated-qa-tests
