version: 2.1
    

executors:
  python-executor:
    docker:
    - image: circleci/python:3.6

commands:
  docker-pull:
    steps:
    - run: echo "Pulling docker image"

  deploy-to-kubernetes:
    steps:
    - run: echo "Deploying to Kubernetes"
    - run: echo "Tagging stage to github"

jobs:
  build:
    executor: python-executor
    steps:
    - checkout
    - run: echo "Linting"
    - run: echo "Running Unit Test"
    - run: echo "Building docker image"
    - run: echo "Running Component tests on docker container"
    - run: echo "Pushing versioned docker image to ECS"

  deploy-to-ci:
    executor: python-executor
    steps:
    - docker-pull
    - deploy-to-kubernetes

  run-integration-tests:
    executor: python-executor
    steps:
    - run: echo "Running automated integration tests"

  tag-qa:
    machine: true
    steps:
            - checkout
            - add_ssh_keys:
                fingerprints:
                - "85:4f:eb:ce:f9:53:72:72:bd:11:14:84:d0:63:4d:2a"
            - run: |
                git config credential.helper 'cache --timeout=120'
                git config --global user.email circleci@build
                git config --global user.name CircleCI
                git config --global pager.tag false
            - run: ./promote.sh qa


  deploy-to-qa:
    executor: python-executor
    steps:
    - docker-pull
    - deploy-to-kubernetes

  run-automated-qa-tests:
    executor: python-executor
    steps:
    - docker-pull
    - deploy-to-kubernetes
    - run: echo "Run Automated QA Tests"


workflows:
  version: 2.1

  ci:
    jobs:
    - build
    - deploy-to-ci:
        requires:
        - build
    - run-integration-tests:
        requires:
        - deploy-to-ci
    - tag-qa:
        requires:
        - run-integration-tests
                

  qa:
    jobs:
    - pull-into-qa:
        type: approval
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /^qa-v[0-9]+(\.[0-9]+)*$/
    - deploy-to-qa:
        requires:
        - pull-into-qa
        filters:
          branches:
            only: master

    - run-automated-qa-tests:
        requires:
        - deploy-to-qa
        filters:
          branches:
            only: master
    - confirm-qa-ok:
        type: approval
        requires:
        - run-automated-qa-tests
        filters:
          branches:
            only: master
