version: 2
    
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: echo "Linting..."
      - run: echo "Running Unit Test..."
      - run: echo "Building docker Image...."
      - run: echo "Running Component tests..."
      - run: echo "pushing docker image to ECS..."

workflows:
  version: 2
  tests:
    jobs:
      - build
