version: 2.1
    

references:
  base: &base
    docker:
      - image: circleci/python:3.6

  qa-filters: &qa-filters
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^qa-v[0-9]+(\.[0-9]+)*$/


  staging-filters: &staging-filters
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /^staging-v[0-9]+(\.[0-9]+)*$/

  git-setup:
    - run: |
        git config credential.helper 'cache --timeout=120'
        git config --global user.email circleci@build
        git config --global user.name CircleCI
        git config --global pager.tag false

commands:

  docker-pull:
    parameters:
      image:
        type: string
        default: "Error No image paramater provided"
    steps:
    - run: echo "Pulling docker image << parameters.image >>"

  deploy-to-kubernetes:
    parameters:
      image:
        type: string
        default: "Error No image paramater provided"
    steps:
    - run: echo "Deploying << parameters.image >> to Kubernetes"

jobs:
  start-ci:
    machine: true
    steps:
      - checkout
      - run: docker run --rm -v ${PWD}:/app treeder/bump patch
      - persist_to_workspace:
          root: .
          paths: VERSION



  general-ci:
    <<: *base
    steps:
    - checkout
    - attach_workspace:
        at: .
    - run: echo "Linting"
    - run: echo "Running Unit Test"
    - run: echo "Building docker image"
    - run: echo "Running Component tests"
    - run: |
        echo "Tagging docker image: my-image:$(cat VERSION)"
    - run: echo "Push to ECR"

  build-win:
    <<: *base
    steps:
      - run: echo "Some Windows specific things..."
  build-osx:
    <<: *base
    steps:
      - run: echo "Some OSX specific things..."

  integration-tests:
    <<: *base
    steps:
    - run: echo "Test if backend version is compatible"
    - run: echo "Running automated integration tests"

  promote-to:
    machine: true
    parameters:
      env:
        type: string
    steps:
            - checkout
            - attach_workspace:
                at: .
            - add_ssh_keys:
                fingerprints:
                - "85:4f:eb:ce:f9:53:72:72:bd:11:14:84:d0:63:4d:2a"
            - run: |
                git config credential.helper 'cache --timeout=120'
                git config --global user.email circleci@build
                git config --global user.name CircleCI
                git config --global pager.tag false
            - run: git add . && git commit -m "Version $(cat VERSION) << parameters.env >> [skip ci]"
            - run: git push origin master
            - run: ./promote.sh << parameters.env >>


  deploy-to:
    <<: *base
    parameters:
      env:
        type: string
    steps:
    - attach_workspace:
        at: .
    - docker-pull:
        image: "my-image-$(cat VERSION)"
    - deploy-to-kubernetes:
        image: "my-image-$(cat VERSION)"


  qa-tests-general:
    <<: *base
    steps:
    - docker-pull
    - deploy-to-kubernetes
    - run: echo "Run automated QA Tests"

  qa-tests-win:
    <<: *base
    steps:
    - run: echo "Run automated Windows QA Tests"

  qa-tests-osx:
    <<: *base
    steps:
    - run: echo "Run automated OSX QA Tests"

  run-stress-tests:
    <<: *base
    steps:
    - run: echo "Run stress tests"


workflows:
  version: 2.1

  ci:
    jobs:
    - start-ci
    - general-ci:
        requires:
          - start-ci
    - build-win:
        requires:
        - general-ci
    - build-osx:
        requires:
        - general-ci
    - deploy-to:
        name: deploy-to-ci
        env: ci
        requires:
        - build-win
        - build-osx
    - integration-tests:
        requires:
        - deploy-to-ci
    - promote-to:
        name: promote-to-qa
        env: qa
        requires:
        - integration-tests
                

  qa:
    jobs:
    - start-qa:
        type: approval
        <<: *qa-filters
    - deploy-to:
        name: deploy-to-qa
        env: qa
        requires:
        - start-qa
        <<: *qa-filters

    - qa-tests-general:
        requires:
        - deploy-to-qa
        <<: *qa-filters

    - qa-tests-win:
        requires:
        - qa-tests-general
        <<: *qa-filters

    - qa-tests-osx:
        requires:
        - qa-tests-general
        <<: *qa-filters

    - confirm-qa:
        type: approval
        requires:
        - qa-tests-win
        - qa-tests-osx
        <<: *qa-filters
    - promote-to:
        name: promote-to-staging
        env: staging
        requires:
        - confirm-qa
        <<: *qa-filters


  staging:
    jobs:
    - start-staging:
        type: approval
        <<: *staging-filters
    - deploy-to:
        name: deploy-to-staging
        env: staging
        requires:
        - start-staging
        <<: *staging-filters

    - run-stress-tests:
        requires:
        - deploy-to-staging
        <<: *staging-filters

    - confirm-qa:
        type: approval
        requires:
        -  run-stress-tests
        <<: *staging-filters

    - promote-to:
        name: promote-to-prod
        env: prod
        requires:
        - confirm-qa
        <<: *qa-filters